[workspace]
members = [
    "node",
    "pallets/template",
    "pallets/organization-identity",
    "pallets/fungible-assets",
    "pallets/non-fungible-assets",
    "runtime",
]
[profile.release]
panic = "unwind"
