name: Renovate
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.186.1
        with:
          configurationFile: .renovaterc.json
          token: ${{ secrets.RENOVATE_TOKEN }}
